version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    deploy:
      mode: global
    volumes:
      - /PATH_TO_YOUR_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: always
    privileged: true
    network_mode: host
    ports:
      - 8123:8123


      # docker swarm init
      ###manager docker swarm join --token SWMTKN-1-0cp0oa4r0fi1hho4cuiq6mqkffbybxifvd9b4f1zdwt3v1y7un-4930hxtikoi5oz7p63zxecra0 172.16.20.180:2377
      ###worker  docker swarm join --token SWMTKN-1-0cp0oa4r0fi1hho4cuiq6mqkffbybxifvd9b4f1zdwt3v1y7un-4930hxtikoi5oz7p63zxecra0 
      # docker stack deploy -c docker-compose.yaml HA 
